### ISSUE TITLE
unsupported function event

### ISSUE THREAD

**Issue by somatorio** [bilby91/serverless-aws-kinesis-firehose#1]
When I try to use this I get the following warning on `serverless deploy`

```
Warning: Invalid configuration encountered
  at 'functions.dataTransform.events.0': unsupported function event

Learn more about configuration validation here: http://slss.io/configuration-validation
```

serverless.yaml:
```
service: kinesis-stream-processor

frameworkVersion: '3'

provider: 
  name: aws
  region: eu-west-1
  runtime: nodejs16.x
  timeout: 60

package:
  individually: true

functions:
  dataTransform:
    handler: src/main.cfRealtimeProcessor
    events:
      - firehose:
          deliveryStreamName: name-of-the-stream
          numberOfRetries: '1'
          bufferSizeInMBs: '1' # Between 1.0 and 3
          bufferIntervalInSeconds: '900' # Between 60 and 900


plugins:
  - serverless-webpack
  - serverless-aws-kinesis-firehose
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: "yarn"
    excludeFiles: "**/src/**/*.spec.ts"
```

I know it is not being updated in 4 years, but that's the only plugin I have found for attaching to a kinesis data firehose, so if you could help me it would be great, thanks :)
